<a href="https://colab.research.google.com/github/deepsarka/customer-churn-analytics-dashboard/blob/main/Customer_churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
data = pd.read_csv('/content/drive/MyDrive/Customer churn data set/customer_churn_1M.csv')

In [3]:
data.head()

,customer_id,signup_date,age,gender,annual_income,education,marital_status,dependents,tenure,contract,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
0,CUST0000000001,2022-12-12 12:53:58.199463,43,Female,55085.25,college,married,1,2,two_year,...,1,1,9.0,0.0,0,0,109.63,16,NaN,0
1,CUST0000000002,2022-01-13 12:53:58.199973,18,Male,60786.11,master,married,1,22,one_year,...,0,1,7.0,0.0,3,1,63.25,134,585.0,0
2,CUST0000000003,2023-09-04 12:53:58.199985,38,Female,73184.32,high_school,widowed,0,3,two_year,...,1,0,6.0,1.0,1,0,47.77,11,632.0,0
3,CUST0000000004,2022-06-27 12:53:58.199992,44,Male,40923.78,high_school,married,1,6,two_year,...,0,1,5.0,2.0,2,1,50.82,6,569.0,0
4,CUST0000000005,2022-12-08 12:53:58.199999,45,Female,36400.94,bachelor,single,0,9,two_year,...,0,1,8.0,1.0,1,0,16.74,18,657.0,0

In [4]:
data.shape

(1000000, 32)

In [5]:
data.isnull().sum()

customer_id                        0
signup_date                        0
age                                0
gender                             0
annual_income                  29959
education                          0
marital_status                     0
dependents                         0
tenure                             0
contract                           0
payment_method                     0
paperless_billing                  0
senior_citizen                     0
monthlycharges                     0
totalcharges                       0
num_services                       0
has_phone_service                  0
has_internet_service               0
has_online_security                0
has_online_backup                  0
has_device_protection              0
has_tech_support                   0
has_streaming_tv                   0
has_streaming_movies               0
customer_satisfaction          19921
num_complaints                 29906
num_service_calls                  0
late_payments                      0
avg_monthly_gb                 50012
days_since_last_interaction        0
credit_score                   40395
churn                              0
dtype: int64

## Data Card

This data card provides a description for each column in the `customer_churn_1M.csv` dataset.

| Column Name                   | Description                                                |
| :---------------------------- | :--------------------------------------------------------- |
| `customer_id`                 | Unique identifier for each customer.                       |
| `signup_date`                 | Date and time when the customer signed up.                 |
| `age`                         | Age of the customer.                                       |
| `gender`                      | Gender of the customer (e.g., 'Female', 'Male').           |
| `annual_income`               | Customer's annual income.                                  |
| `education`                   | Customer's highest education level.                        |
| `marital_status`              | Marital status of the customer.                            |
| `dependents`                  | Number of dependents the customer has.                     |
| `tenure`                      | Number of months the customer has been with the company.   |
| `contract`                    | Type of contract the customer has (e.g., 'one_year', 'two_year'). |
| `payment_method`              | Method of payment used by the customer.                    |
| `paperless_billing`           | Indicates if the customer uses paperless billing (0 = No, 1 = Yes). |
| `senior_citizen`              | Indicates if the customer is a senior citizen (0 = No, 1 = Yes). |
| `monthlycharges`              | Monthly charges for the customer's services.               |
| `totalcharges`                | Total charges incurred by the customer over their tenure.  |
| `num_services`                | Number of services the customer is subscribed to.          |
| `has_phone_service`           | Indicates if the customer has phone service (0 = No, 1 = Yes). |
| `has_internet_service`        | Indicates if the customer has internet service (0 = No, 1 = Yes). |
| `has_online_security`         | Indicates if the customer has online security service (0 = No, 1 = Yes). |
| `has_online_backup`           | Indicates if the customer has online backup service (0 = No, 1 = Yes). |
| `has_device_protection`       | Indicates if the customer has device protection service (0 = No, 1 = Yes). |
| `has_tech_support`            | Indicates if the customer has tech support service (0 = No, 1 = Yes). |
| `has_streaming_tv`            | Indicates if the customer has streaming TV service (0 = No, 1 = Yes). |
| `has_streaming_movies`        | Indicates if the customer has streaming movies service (0 = No, 1 = Yes). |
| `customer_satisfaction`       | Customer satisfaction score (typically 1-10).              |
| `num_complaints`              | Number of complaints made by the customer.                 |
| `num_service_calls`           | Number of service calls made by the customer.              |
| `late_payments`               | Number of late payments made by the customer.              |
| `avg_monthly_gb`              | Average monthly gigabytes used by the customer.            |
| `days_since_last_interaction` | Number of days since the customer's last interaction.      |
| `credit_score`                | Customer's credit score.                                   |
| `churn`                       | Target variable: Indicates if the customer churned (0 = No, 1 = Yes). |

In [6]:
data["annual_income"].describe()
data["customer_satisfaction"].describe()

count    980079.000000
mean          6.159110
std           2.328287
min           1.000000
25%           4.000000
50%           7.000000
75%           8.000000
max           9.000000
Name: customer_satisfaction, dtype: float64

In [7]:
data['annual_income'].fillna(data['annual_income'].median(), inplace=True)

/tmp/ipykernel_1036/2659934545.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['annual_income'].fillna(data['annual_income'].median(), inplace=True)

In [8]:
data['customer_satisfaction'].fillna(data['customer_satisfaction'].median(), inplace=True)

/tmp/ipykernel_1036/1824623254.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['customer_satisfaction'].fillna(data['customer_satisfaction'].median(), inplace=True)

In [9]:
data['num_complaints'].fillna(0, inplace=True)

/tmp/ipykernel_1036/1289808882.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['num_complaints'].fillna(0, inplace=True)

In [10]:
data["avg_monthly_gb"].describe()

count    949988.000000
mean         39.095179
std          43.852564
min           0.000000
25%          12.840000
50%          27.770000
75%          51.230000
max         557.824023
Name: avg_monthly_gb, dtype: float64

In [11]:
data['avg_monthly_gb'].fillna(data['avg_monthly_gb'].median(), inplace=True)

/tmp/ipykernel_1036/3786027456.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['avg_monthly_gb'].fillna(data['avg_monthly_gb'].median(), inplace=True)

In [12]:
data["credit_score"].describe()

count    959605.000000
mean        678.562134
std          87.642951
min         300.000000
25%         619.000000
50%         680.000000
75%         740.000000
max         850.000000
Name: credit_score, dtype: float64

In [13]:
data['credit_score'].fillna(data['credit_score'].median(), inplace=True)

/tmp/ipykernel_1036/3661624155.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['credit_score'].fillna(data['credit_score'].median(), inplace=True)

In [14]:
data.duplicated().sum()

np.int64(0)

In [15]:
data['churn'].value_counts(normalize=True) * 100

churn
0    90.0773
1     9.9227
Name: proportion, dtype: float64

In [16]:
(data['totalcharges'] - (data['monthlycharges'] * data['tenure'])).describe()

count    1000000.000000
mean         -97.105181
std          581.707901
min       -57060.348432
25%         -107.880000
50%           -9.010000
75%           35.200000
max         5978.461508
dtype: float64

In [17]:
data['tenure'].describe()

count    1000000.000000
mean          22.381923
std           20.073341
min            1.000000
25%            6.000000
50%           16.000000
75%           33.000000
max           72.000000
Name: tenure, dtype: float64

In [18]:
data['signup_date'].min()

'2021-01-13 12:53:58.205311'

In [19]:
data['signup_date'].max()

'2026-01-11 12:54:09.480291'

In [20]:
data[['has_phone_service','has_internet_service','has_online_security','has_online_backup','has_device_protection','has_tech_support','has_streaming_tv','has_streaming_movies']].describe()

,has_phone_service,has_internet_service,has_online_security,has_online_backup,has_device_protection,has_tech_support,has_streaming_tv,has_streaming_movies
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000
mean,0.769551,0.849742,0.339468,0.425723,0.297082,0.497344,0.59999,0.549086
std,0.421120,0.357324,0.473529,0.494452,0.456973,0.499993,0.48990,0.497585
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000

In [21]:
data[['num_services']].describe()

         num_services
count  1000000.000000
mean         2.563721
std          1.412330
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max          6.000000

In [22]:
service_cols = ['has_phone_service','has_internet_service','has_online_security','has_online_backup','has_device_protection','has_tech_support','has_streaming_tv','has_streaming_movies']

data['services_sum_check'] = data[service_cols].sum(axis=1)

data[['num_services','services_sum_check']].corr()

                    num_services  services_sum_check
num_services            1.000000            0.000295
services_sum_check      0.000295            1.000000

In [23]:
data.drop(columns=['services_sum_check'], inplace=True)

In [24]:
tenure = data['tenure_bucket'] = pd.cut(data['tenure'], bins=[0,6,12,24,48,72], labels=['0-6mo','6-12mo','1-2yr','2-4yr','4-6yr'])
tenure

0          0-6mo
1          1-2yr
2          0-6mo
3          0-6mo
4         6-12mo
           ...
999995     0-6mo
999996    6-12mo
999997    6-12mo
999998     1-2yr
999999     0-6mo
Name: tenure, Length: 1000000, dtype: category
Categories (5, object): ['0-6mo' < '6-12mo' < '1-2yr' < '2-4yr' < '4-6yr']

In [25]:
data['signup_date'] = pd.to_datetime(data['signup_date'])

In [26]:
date=data['signup_year'] = data['signup_date'].dt.year
date

0         2022
1         2022
2         2023
3         2022
4         2022
          ...
999995    2025
999996    2024
999997    2021
999998    2025
999999    2023
Name: signup_date, Length: 1000000, dtype: int32

In [27]:
income = data['income_bracket'] = pd.cut(data['annual_income'], bins=[0,30000,60000,100000,250000], labels=['Low','Mid','High','Very High'])
income

0               Mid
1              High
2              High
3               Mid
4               Mid
            ...
999995          Low
999996    Very High
999997          Mid
999998          Mid
999999          Low
Name: annual_income, Length: 1000000, dtype: category
Categories (4, object): ['Low' < 'Mid' < 'High' < 'Very High']

In [28]:
has_complained_flag = data['complaint_flag'] = (data['num_complaints'] > 0).astype(int)
has_complained_flag

0         0
1         0
2         1
3         1
4         1
         ..
999995    1
999996    0
999997    0
999998    0
999999    0
Name: num_complaints, Length: 1000000, dtype: int64

In [29]:
high_usage_flag = data['high_usage_flag'] = (data['avg_monthly_gb'] > data['avg_monthly_gb'].median()).astype(int)
high_usage_flag

0         1
1         1
2         1
3         1
4         0
         ..
999995    0
999996    0
999997    0
999998    0
999999    0
Name: avg_monthly_gb, Length: 1000000, dtype: int64

In [30]:
from IPython.display import display

churn_rate_new_feature = [
    "tenure_bucket",
    "income_bracket",
    "complaint_flag",
    "contract",
    "high_usage_flag"
]

for col in churn_rate_new_feature:
    print(f"\n📊 Churn Rate by {col}")
    display(data.groupby(col)["churn"].mean().to_frame("Churn Rate"))

📊 Churn Rate by tenure_bucket

/tmp/ipykernel_1036/1298978967.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  display(data.groupby(col)["churn"].mean().to_frame("Churn Rate"))

               Churn Rate
tenure_bucket
0-6mo            0.103922
6-12mo           0.100541
1-2yr            0.099886
2-4yr            0.096374
4-6yr            0.092165

📊 Churn Rate by income_bracket

/tmp/ipykernel_1036/1298978967.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  display(data.groupby(col)["churn"].mean().to_frame("Churn Rate"))

                Churn Rate
income_bracket
Low               0.099293
Mid               0.099219
High              0.098738
Very High         0.100184

📊 Churn Rate by complaint_flag

                Churn Rate
complaint_flag
0                 0.082032
1                 0.117207

📊 Churn Rate by contract

                Churn Rate
contract
month_to_month    0.265056
one_year          0.126531
two_year          0.056519

📊 Churn Rate by high_usage_flag

                 Churn Rate
high_usage_flag
0                  0.101050
1                  0.097212

In [31]:
# data.to_csv('/content/drive/MyDrive/Customer churn data set/customer_churn_cleaned.csv', index=False)

In [32]:
data.dtypes

customer_id                            object
signup_date                    datetime64[ns]
age                                     int64
gender                                 object
annual_income                         float64
education                              object
marital_status                         object
dependents                              int64
tenure                                  int64
contract                               object
payment_method                         object
paperless_billing                      object
senior_citizen                          int64
monthlycharges                        float64
totalcharges                          float64
num_services                            int64
has_phone_service                       int64
has_internet_service                    int64
has_online_security                     int64
has_online_backup                       int64
has_device_protection                   int64
has_tech_support                        int64
has_streaming_tv                        int64
has_streaming_movies                    int64
customer_satisfaction                 float64
num_complaints                        float64
num_service_calls                       int64
late_payments                           int64
avg_monthly_gb                        float64
days_since_last_interaction             int64
credit_score                          float64
churn                                   int64
tenure_bucket                        category
signup_year                             int32
income_bracket                       category
complaint_flag                          int64
high_usage_flag                         int64
dtype: object